# Default values for .
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/nmaupu/freenas-provisioner
  tag: 2.4
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

provisioner:
  datasetParentName: pool1/k8s
  serverSecretName: freenas-nfs-values


nodeSelector: {}

tolerations: []

affinity: {}